#!/bin/sh

#Script SQL untuk pembuatan view laporan per sekolah Kab. Balangan



#cat buku_penerimaan_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_ajung/g | sed -e s/355/355/g > buku_penerimaan_sdn_ajung.sql

cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_ambakiang_hulu/g | sed -e s/355/193/g > buku_pengeluaran_sdn_ambakiang_hulu.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_aniyungan/g | sed -e s/355/311/g > buku_pengeluaran_sdn_aniyungan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_auh/g | sed -e s/355/356/g > buku_pengeluaran_sdn_auh.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_badalungga/g | sed -e s/355/194/g > buku_pengeluaran_sdn_badalungga.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_badalungga_hilir/g | sed -e s/355/195/g > buku_pengeluaran_sdn_badalungga_hilir.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_bakung/g | sed -e s/355/227/g > buku_pengeluaran_sdn_bakung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_balida/g | sed -e s/355/160/g > buku_pengeluaran_sdn_balida.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_banua_hanyar/g | sed -e s/355/228/g > buku_pengeluaran_sdn_banua_hanyar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baramban/g | sed -e s/355/196/g > buku_pengeluaran_sdn_baramban.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baru/g | sed -e s/355/197/g > buku_pengeluaran_sdn_baru.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baruh_bahinu_dalam/g | sed -e s/355/371/g > buku_pengeluaran_sdn_baruh_bahinu_dalam.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baruh_bahinu_luar/g | sed -e s/355/372/g > buku_pengeluaran_sdn_baruh_bahinu_luar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baruh_penyambaran_1/g | sed -e s/355/312/g > buku_pengeluaran_sdn_baruh_penyambaran_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_baruh_penyambaran_2/g | sed -e s/355/313/g > buku_pengeluaran_sdn_baruh_penyambaran_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_bata/g | sed -e s/355/267/g > buku_pengeluaran_sdn_bata.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_batu_merah_1/g | sed -e s/355/119/g > buku_pengeluaran_sdn_batu_merah_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_batu_merah_3/g | sed -e s/355/120/g > buku_pengeluaran_sdn_batu_merah_3.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_batu_piring/g | sed -e s/355/373/g > buku_pengeluaran_sdn_batu_piring.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_bayur/g | sed -e s/355/198/g > buku_pengeluaran_sdn_bayur.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_belanti/g | sed -e s/355/199/g > buku_pengeluaran_sdn_belanti.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_binjai_punggal_1/g | sed -e s/355/314/g > buku_pengeluaran_sdn_binjai_punggal_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_binjai_punggal_2/g | sed -e s/355/315/g > buku_pengeluaran_sdn_binjai_punggal_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_binju/g | sed -e s/355/316/g > buku_pengeluaran_sdn_binju.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_binuang_santang/g | sed -e s/355/317/g > buku_pengeluaran_sdn_binuang_santang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_bungur/g | sed -e s/355/229/g > buku_pengeluaran_sdn_bungur.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_buntu_karau_1/g | sed -e s/355/268/g > buku_pengeluaran_sdn_buntu_karau_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_dahai/g | sed -e s/355/161/g > buku_pengeluaran_sdn_dahai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_danau_banta/g | sed -e s/355/162/g > buku_pengeluaran_sdn_danau_banta.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_dayak_pitap/g | sed -e s/355/357/g > buku_pengeluaran_sdn_dayak_pitap.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_galumbang_juai/g | sed -e s/355/269/g > buku_pengeluaran_sdn_galumbang_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_galumbang_paringin_selatan/g | sed -e s/355/374/g > buku_pengeluaran_sdn_galumbang_paringin_selatan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gampa/g | sed -e s/355/375/g > buku_pengeluaran_sdn_gampa.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_guha_1/g | sed -e s/355/230/g > buku_pengeluaran_sdn_guha_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_guha_2/g | sed -e s/355/231/g > buku_pengeluaran_sdn_guha_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gulinggang/g | sed -e s/355/270/g > buku_pengeluaran_sdn_gulinggang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gunung_manau/g | sed -e s/355/232/g > buku_pengeluaran_sdn_gunung_manau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gunung_pandau/g | sed -e s/355/163/g > buku_pengeluaran_sdn_gunung_pandau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gunung_riut_1/g | sed -e s/355/318/g > buku_pengeluaran_sdn_gunung_riut_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_gunung_riut_2/g | sed -e s/355/319/g > buku_pengeluaran_sdn_gunung_riut_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_halong_1/g | sed -e s/355/320/g > buku_pengeluaran_sdn_halong_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_halong_2/g | sed -e s/355/321/g > buku_pengeluaran_sdn_halong_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_halong_3/g | sed -e s/355/322/g > buku_pengeluaran_sdn_halong_3.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_halubau/g | sed -e s/355/376/g > buku_pengeluaran_sdn_halubau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_halubau_utara/g | sed -e s/355/377/g > buku_pengeluaran_sdn_halubau_utara.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hamarung_1/g | sed -e s/355/271/g > buku_pengeluaran_sdn_hamarung_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hamarung_2/g | sed -e s/355/272/g > buku_pengeluaran_sdn_hamarung_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hamparaya/g | sed -e s/355/233/g > buku_pengeluaran_sdn_hamparaya.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hauwai_1/g | sed -e s/355/323/g > buku_pengeluaran_sdn_hauwai_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hauwai_2/g | sed -e s/355/324/g > buku_pengeluaran_sdn_hauwai_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hilir_pasar/g | sed -e s/355/121/g > buku_pengeluaran_sdn_hilir_pasar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hujan_amas_1/g | sed -e s/355/164/g > buku_pengeluaran_sdn_hujan_amas_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hujan_amas_2/g | sed -e s/355/165/g > buku_pengeluaran_sdn_hujan_amas_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_hukai/g | sed -e s/355/273/g > buku_pengeluaran_sdn_hukai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_inan/g | sed -e s/355/378/g > buku_pengeluaran_sdn_inan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_jimamun/g | sed -e s/355/122/g > buku_pengeluaran_sdn_jimamun.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_ju_uh/g | sed -e s/355/358/g > buku_pengeluaran_sdn_ju_uh.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_juai/g | sed -e s/355/274/g > buku_pengeluaran_sdn_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_jungkal/g | sed -e s/355/123/g > buku_pengeluaran_sdn_jungkal.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kaladan/g | sed -e s/355/379/g > buku_pengeluaran_sdn_kaladan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kalahiang/g | sed -e s/355/166/g > buku_pengeluaran_sdn_kalahiang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kambiyain/g | sed -e s/355/359/g > buku_pengeluaran_sdn_kambiyain.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kandang_jaya/g | sed -e s/355/124/g > buku_pengeluaran_sdn_kandang_jaya.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kapul/g | sed -e s/355/325/g > buku_pengeluaran_sdn_kapul.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_karuh/g | sed -e s/355/234/g > buku_pengeluaran_sdn_karuh.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kasai/g | sed -e s/355/235/g > buku_pengeluaran_sdn_kasai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kupang/g | sed -e s/355/125/g > buku_pengeluaran_sdn_kupang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kusambi_hilir/g | sed -e s/355/126/g > buku_pengeluaran_sdn_kusambi_hilir.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kusambi_hulu_1/g | sed -e s/355/127/g > buku_pengeluaran_sdn_kusambi_hulu_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_kusambi_hulu_2/g | sed -e s/355/128/g > buku_pengeluaran_sdn_kusambi_hulu_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lajar/g | sed -e s/355/129/g > buku_pengeluaran_sdn_lajar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lalayau_1/g | sed -e s/355/275/g > buku_pengeluaran_sdn_lalayau_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lalayau_2/g | sed -e s/355/276/g > buku_pengeluaran_sdn_lalayau_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lamida_atas/g | sed -e s/355/167/g > buku_pengeluaran_sdn_lamida_atas.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lampihong_kanan/g | sed -e s/355/130/g > buku_pengeluaran_sdn_lampihong_kanan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lampihong_kiri/g | sed -e s/355/131/g > buku_pengeluaran_sdn_lampihong_kiri.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_langkap/g | sed -e s/355/360/g > buku_pengeluaran_sdn_langkap.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lasung_batu_1/g | sed -e s/355/168/g > buku_pengeluaran_sdn_lasung_batu_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lasung_batu_2/g | sed -e s/355/169/g > buku_pengeluaran_sdn_lasung_batu_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lingsir/g | sed -e s/355/380/g > buku_pengeluaran_sdn_lingsir.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lok_batu/g | sed -e s/355/236/g > buku_pengeluaran_sdn_lok_batu.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lok_batung/g | sed -e s/355/170/g > buku_pengeluaran_sdn_lok_batung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lok_hamawang/g | sed -e s/355/143/g > buku_pengeluaran_sdn_lok_hamawang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_lok_panginangan/g | sed -e s/355/142/g > buku_pengeluaran_sdn_lok_panginangan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_malihu/g | sed -e s/355/171/g > buku_pengeluaran_sdn_malihu.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mamantang/g | sed -e s/355/326/g > buku_pengeluaran_sdn_mamantang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mampari/g | sed -e s/355/237/g > buku_pengeluaran_sdn_mampari.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mangkayahu/g | sed -e s/355/172/g > buku_pengeluaran_sdn_mangkayahu.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_maningau/g | sed -e s/355/200/g > buku_pengeluaran_sdn_maningau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mantimin_1/g | sed -e s/355/238/g > buku_pengeluaran_sdn_mantimin_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mantimin_2/g | sed -e s/355/239/g > buku_pengeluaran_sdn_mantimin_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mantuyan/g | sed -e s/355/327/g > buku_pengeluaran_sdn_mantuyan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_maradap/g | sed -e s/355/381/g > buku_pengeluaran_sdn_maradap.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_marias/g | sed -e s/355/277/g > buku_pengeluaran_sdn_marias.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_matang_hanau/g | sed -e s/355/132/g > buku_pengeluaran_sdn_matang_hanau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mauya/g | sed -e s/355/328/g > buku_pengeluaran_sdn_mauya.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mayanau/g | sed -e s/355/361/g > buku_pengeluaran_sdn_mayanau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_merah/g | sed -e s/355/201/g > buku_pengeluaran_sdn_merah.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mihu_1/g | sed -e s/355/278/g > buku_pengeluaran_sdn_mihu_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mihu_2/g | sed -e s/355/279/g > buku_pengeluaran_sdn_mihu_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_muara_jaya/g | sed -e s/355/202/g > buku_pengeluaran_sdn_muara_jaya.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_muara_ninian/g | sed -e s/355/280/g > buku_pengeluaran_sdn_muara_ninian.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_muara_pitap/g | sed -e s/355/382/g > buku_pengeluaran_sdn_muara_pitap.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mundar/g | sed -e s/355/133/g > buku_pengeluaran_sdn_mundar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_mungkur_uyam/g | sed -e s/355/281/g > buku_pengeluaran_sdn_mungkur_uyam.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_munjung/g | sed -e s/355/240/g > buku_pengeluaran_sdn_munjung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_murung_abuin/g | sed -e s/355/383/g > buku_pengeluaran_sdn_murung_abuin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_murung_ilung/g | sed -e s/355/173/g > buku_pengeluaran_sdn_murung_ilung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_nungka/g | sed -e s/355/203/g > buku_pengeluaran_sdn_nungka.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pamurus/g | sed -e s/355/282/g > buku_pengeluaran_sdn_pamurus.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_panaitan/g | sed -e s/355/134/g > buku_pengeluaran_sdn_panaitan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_panikin/g | sed -e s/355/362/g > buku_pengeluaran_sdn_panikin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_paringin_1/g | sed -e s/355/174/g > buku_pengeluaran_sdn_paringin_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_paringin_2/g | sed -e s/355/175/g > buku_pengeluaran_sdn_paringin_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_paringin_selatan_1/g | sed -e s/355/384/g > buku_pengeluaran_sdn_paringin_selatan_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_paringin_timur/g | sed -e s/355/176/g > buku_pengeluaran_sdn_paringin_timur.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pelajau/g | sed -e s/355/241/g > buku_pengeluaran_sdn_pelajau.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pematang/g | sed -e s/355/204/g > buku_pengeluaran_sdn_pematang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pimping/g | sed -e s/355/135/g > buku_pengeluaran_sdn_pimping.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_piyait/g | sed -e s/355/205/g > buku_pengeluaran_sdn_piyait.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pulantan/g | sed -e s/355/206/g > buku_pengeluaran_sdn_pulantan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_pulau_kambang/g | sed -e s/355/207/g > buku_pengeluaran_sdn_pulau_kambang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_putat_basiun/g | sed -e s/355/208/g > buku_pengeluaran_sdn_putat_basiun.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_puyun/g | sed -e s/355/329/g > buku_pengeluaran_sdn_puyun.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_riwa/g | sed -e s/355/242/g > buku_pengeluaran_sdn_riwa.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sei_kusi/g | sed -e s/355/243/g > buku_pengeluaran_sdn_sei_kusi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_simpang_tiga/g | sed -e s/355/136/g > buku_pengeluaran_sdn_simpang_tiga.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sirap_1/g | sed -e s/355/283/g > buku_pengeluaran_sdn_sirap_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sirap_2/g | sed -e s/355/284/g > buku_pengeluaran_sdn_sirap_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sirap_3/g | sed -e s/355/285/g > buku_pengeluaran_sdn_sirap_3.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sumpung/g | sed -e s/355/244/g > buku_pengeluaran_sdn_sumpung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungai_batung/g | sed -e s/355/286/g > buku_pengeluaran_sdn_sungai_batung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungai_hanyar/g | sed -e s/355/245/g > buku_pengeluaran_sdn_sungai_hanyar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungai_ketapi/g | sed -e s/355/177/g > buku_pengeluaran_sdn_sungai_ketapi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungai_pumpung/g | sed -e s/355/209/g > buku_pengeluaran_sdn_sungai_pumpung.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungai_tabuk/g | sed -e s/355/137/g > buku_pengeluaran_sdn_sungai_tabuk.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_sungsum/g | sed -e s/355/363/g > buku_pengeluaran_sdn_sungsum.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tabuan_1/g | sed -e s/355/330/g > buku_pengeluaran_sdn_tabuan_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tabuan_2/g | sed -e s/355/331/g > buku_pengeluaran_sdn_tabuan_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tampang/g | sed -e s/355/138/g > buku_pengeluaran_sdn_tampang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tanah_habang_kanan_1/g | sed -e s/355/139/g > buku_pengeluaran_sdn_tanah_habang_kanan_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tanah_habang_kanan_2/g | sed -e s/355/140/g > buku_pengeluaran_sdn_tanah_habang_kanan_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tanah_habang_kiri/g | sed -e s/355/141/g > buku_pengeluaran_sdn_tanah_habang_kiri.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tarangan/g | sed -e s/355/385/g > buku_pengeluaran_sdn_tarangan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tawahan_1/g | sed -e s/355/287/g > buku_pengeluaran_sdn_tawahan_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tawahan_2/g | sed -e s/355/296/g > buku_pengeluaran_sdn_tawahan_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tebing_tinggi/g | sed -e s/355/364/g > buku_pengeluaran_sdn_tebing_tinggi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_telaga_purun/g | sed -e s/355/386/g > buku_pengeluaran_sdn_telaga_purun.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_teluk_bayur_2/g | sed -e s/355/288/g > buku_pengeluaran_sdn_teluk_bayur_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_teluk_bayur_3/g | sed -e s/355/289/g > buku_pengeluaran_sdn_teluk_bayur_3.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_teluk_mesjid_1/g | sed -e s/355/246/g > buku_pengeluaran_sdn_teluk_mesjid_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_teluk_mesjid_2/g | sed -e s/355/247/g > buku_pengeluaran_sdn_teluk_mesjid_2.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tigarun/g | sed -e s/355/290/g > buku_pengeluaran_sdn_tigarun.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_timbun_tulang/g | sed -e s/355/248/g > buku_pengeluaran_sdn_timbun_tulang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tundakan/g | sed -e s/355/210/g > buku_pengeluaran_sdn_tundakan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_tundi/g | sed -e s/355/211/g > buku_pengeluaran_sdn_tundi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_u_ungan/g | sed -e s/355/212/g > buku_pengeluaran_sdn_u_ungan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_uren_1/g | sed -e s/355/332/g > buku_pengeluaran_sdn_uren_1.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdn_wangkili/g | sed -e s/355/213/g > buku_pengeluaran_sdn_wangkili.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/skb_balangan/g | sed -e s/355/179/g > buku_pengeluaran_skb_balangan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_awayan/g | sed -e s/355/90/g > buku_pengeluaran_sman_1_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_halong/g | sed -e s/355/91/g > buku_pengeluaran_sman_1_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_juai/g | sed -e s/355/92/g > buku_pengeluaran_sman_1_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_lampihong/g | sed -e s/355/530/g > buku_pengeluaran_sman_1_lampihong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_paringin/g | sed -e s/355/93/g > buku_pengeluaran_sman_1_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_1_tebing_tinggi/g | sed -e s/355/396/g > buku_pengeluaran_sman_1_tebing_tinggi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_2_halong/g | sed -e s/355/528/g > buku_pengeluaran_sman_2_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_2_juai/g | sed -e s/355/529/g > buku_pengeluaran_sman_2_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sman_2_paringin/g | sed -e s/355/94/g > buku_pengeluaran_sman_2_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smk_ppn_paringin/g | sed -e s/355/97/g > buku_pengeluaran_smk_ppn_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smkn_1_batumandi/g | sed -e s/355/95/g > buku_pengeluaran_smkn_1_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smkn_1_paringin/g | sed -e s/355/96/g > buku_pengeluaran_smkn_1_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_awayan/g | sed -e s/355/98/g > buku_pengeluaran_smpn_1_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_batumandi/g | sed -e s/355/99/g > buku_pengeluaran_smpn_1_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_halong/g | sed -e s/355/100/g > buku_pengeluaran_smpn_1_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_juai/g | sed -e s/355/101/g > buku_pengeluaran_smpn_1_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_lampihong/g | sed -e s/355/102/g > buku_pengeluaran_smpn_1_lampihong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_1_paringin/g | sed -e s/355/103/g > buku_pengeluaran_smpn_1_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_awayan/g | sed -e s/355/104/g > buku_pengeluaran_smpn_2_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_batumandi/g | sed -e s/355/105/g > buku_pengeluaran_smpn_2_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_halong/g | sed -e s/355/106/g > buku_pengeluaran_smpn_2_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_juai/g | sed -e s/355/107/g > buku_pengeluaran_smpn_2_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_lampihong/g | sed -e s/355/108/g > buku_pengeluaran_smpn_2_lampihong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_2_paringin/g | sed -e s/355/109/g > buku_pengeluaran_smpn_2_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_3_awayan/g | sed -e s/355/110/g > buku_pengeluaran_smpn_3_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_3_batumandi/g | sed -e s/355/111/g > buku_pengeluaran_smpn_3_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_3_halong/g | sed -e s/355/112/g > buku_pengeluaran_smpn_3_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_3_paringin/g | sed -e s/355/113/g > buku_pengeluaran_smpn_3_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_4_awayan/g | sed -e s/355/114/g > buku_pengeluaran_smpn_4_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_4_batumandi/g | sed -e s/355/397/g > buku_pengeluaran_smpn_4_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_4_halong/g | sed -e s/355/115/g > buku_pengeluaran_smpn_4_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_4_paringin/g | sed -e s/355/116/g > buku_pengeluaran_smpn_4_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_5_halong/g | sed -e s/355/117/g > buku_pengeluaran_smpn_5_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_5_paringin/g | sed -e s/355/118/g > buku_pengeluaran_smpn_5_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_6_halong_satu_atap/g | sed -e s/355/592/g > buku_pengeluaran_smpn_6_halong_satu_atap.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smpn_satu_atap_libaru_sungkai/g | sed -e s/355/614/g > buku_pengeluaran_smpn_satu_atap_libaru_sungkai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/smps_ikhwanul_muslimin/g | sed -e s/355/591/g > buku_pengeluaran_smps_ikhwanul_muslimin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_harapan_bangsa/g | sed -e s/355/300/g > buku_pengeluaran_tk_harapan_bangsa.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_negeri_pembina_awayan/g | sed -e s/355/607/g > buku_pengeluaran_tk_negeri_pembina_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_negeri_pembina_batumandi/g | sed -e s/355/264/g > buku_pengeluaran_tk_negeri_pembina_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_negeri_pembina_juai/g | sed -e s/355/292/g > buku_pengeluaran_tk_negeri_pembina_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_negeri_pembina_paringin/g | sed -e s/355/183/g > buku_pengeluaran_tk_negeri_pembina_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/tk_negeri_pembina_paringin_selatan/g | sed -e s/355/608/g > buku_pengeluaran_tk_negeri_pembina_paringin_selatan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdlb_negeri_paringin/g | sed -e s/355/178/g > buku_pengeluaran_sdlb_negeri_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_tebing_tinggi/g | sed -e s/355/88/g > buku_pengeluaran_upt_kecamatan_tebing_tinggi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_paringin_selatan/g | sed -e s/355/89/g > buku_pengeluaran_upt_kecamatan_paringin_selatan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_paringin/g | sed -e s/355/83/g > buku_pengeluaran_upt_kecamatan_paringin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_lampihong/g | sed -e s/355/82/g > buku_pengeluaran_upt_kecamatan_lampihong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_juai/g | sed -e s/355/86/g > buku_pengeluaran_upt_kecamatan_juai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_halong/g | sed -e s/355/87/g > buku_pengeluaran_upt_kecamatan_halong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_batumandi/g | sed -e s/355/84/g > buku_pengeluaran_upt_kecamatan_batumandi.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/upt_kecamatan_awayan/g | sed -e s/355/85/g > buku_pengeluaran_upt_kecamatan_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/min_tariwin/g | sed -e s/355/249/g > buku_pengeluaran_min_tariwin.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/paud_terpadu_awayan/g | sed -e s/355/536/g > buku_pengeluaran_paud_terpadu_awayan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/rumah_pintar/g | sed -e s/355/609/g > buku_pengeluaran_rumah_pintar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdit_darul_fikri/g | sed -e s/355/590/g > buku_pengeluaran_sdit_darul_fikri.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_ambata/g | sed -e s/355/532/g > buku_pengeluaran_sd_kecil_ambata.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_ampinang/g | sed -e s/355/333/g > buku_pengeluaran_sd_kecil_ampinang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_hampang/g | sed -e s/355/337/g > buku_pengeluaran_sd_kecil_hampang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_kurihai/g | sed -e s/355/531/g > buku_pengeluaran_sd_kecil_kurihai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_libaru_sungkai/g | sed -e s/355/335/g > buku_pengeluaran_sd_kecil_libaru_sungkai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_mabulan/g | sed -e s/355/334/g > buku_pengeluaran_sd_kecil_mabulan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_papuyuan/g | sed -e s/355/144/g > buku_pengeluaran_sd_kecil_papuyuan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_rantau_paku/g | sed -e s/355/366/g > buku_pengeluaran_sd_kecil_rantau_paku.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_raranum/g | sed -e s/355/365/g > buku_pengeluaran_sd_kecil_raranum.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_simpang_nadong/g | sed -e s/355/535/g > buku_pengeluaran_sd_kecil_simpang_nadong.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_tampaan/g | sed -e s/355/534/g > buku_pengeluaran_sd_kecil_tampaan.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_tanjungan_jelamu/g | sed -e s/355/533/g > buku_pengeluaran_sd_kecil_tanjungan_jelamu.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sd_kecil_tinggar/g | sed -e s/355/336/g > buku_pengeluaran_sd_kecil_tinggar.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdk_andamai/g | sed -e s/355/354/g > buku_pengeluaran_sdk_andamai.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdk_mapat/g | sed -e s/355/352/g > buku_pengeluaran_sdk_mapat.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdk_sawang/g | sed -e s/355/351/g > buku_pengeluaran_sdk_sawang.sql
cat buku_pengeluaran_sdn_ajung.sql | sed -e s/sdn_ajung/sdk_sisirin/g | sed -e s/355/353/g > buku_pengeluaran_sdk_sisirin.sql

cat buku_pengeluaran_*.sql > ../gabungan_buku_pengeluaran_sub_skpd.sql
