cat models_tt.py | sed -e s/Tebing\ Tinggi/Setwan/g | sed -e s/TebingTinggi/Setwan/g | sed -e s/38/01/g > model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Setda/g | sed -e s/TebingTinggi/Setda/g | sed -e s/38/02/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPUPR/g | sed -e s/TebingTinggi/DPUPR/g | sed -e s/38/03/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Dishub/g | sed -e s/TebingTinggi/Dishub/g | sed -e s/38/04/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Dinkes/g | sed -e s/TebingTinggi/Dinkes/g | sed -e s/38/05/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BLUD\ RSUD/g | sed -e s/TebingTinggi/BLUDRSUD/g | sed -e s/38/06/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Disdik/g | sed -e s/TebingTinggi/Disdik/g | sed -e s/38/07/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Perpustakaan/g | sed -e s/TebingTinggi/Perpustakaan/g | sed -e s/38/08/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Sosial/g | sed -e s/TebingTinggi/Sosial/g | sed -e s/38/09/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPMD/g | sed -e s/TebingTinggi/DPMD/g | sed -e s/38/10/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPPPA/g | sed -e s/TebingTinggi/DPPPA/g | sed -e s/38/11/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DukCatPil/g | sed -e s/TebingTinggi/DukCatPil/g | sed -e s/38/12/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Pertanian/g | sed -e s/TebingTinggi/Pertanian/g | sed -e s/38/13/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DKP/g | sed -e s/TebingTinggi/DKP/g | sed -e s/38/15/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DKUKMP/g | sed -e s/TebingTinggi/DKUKMP/g | sed -e s/38/16/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPMPTSP/g | sed -e s/TebingTinggi/DPMPTSP/g | sed -e s/38/18/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BKD/g | sed -e s/TebingTinggi/BKD/g | sed -e s/38/19/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Inspektorat/g | sed -e s/TebingTinggi/Inspektorat/g | sed -e s/38/20/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BAPPEDA/g | sed -e s/TebingTinggi/BAPPEDA/g | sed -e s/38/21/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DLH/g | sed -e s/TebingTinggi/DLH/g | sed -e s/38/22/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DKO/g | sed -e s/TebingTinggi/DKO/g | sed -e s/38/23/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/KESBANGPOL/g | sed -e s/TebingTinggi/KESBANGPOL/g | sed -e s/38/24/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/SATPOLPP/g | sed -e s/TebingTinggi/SATPOLPP/g | sed -e s/38/25/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BKPPD/g | sed -e s/TebingTinggi/BKPPD/g | sed -e s/38/26/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Paringin/g | sed -e s/TebingTinggi/Paringin/g | sed -e s/38/28/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Lampihong/g | sed -e s/TebingTinggi/Lampihong/g | sed -e s/38/31/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Batumandi/g | sed -e s/TebingTinggi/Batumandi/g | sed -e s/38/32/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Juai/g | sed -e s/TebingTinggi/Juai/g | sed -e s/38/33/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Awayan/g | sed -e s/TebingTinggi/Awayan/g | sed -e s/38/34/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Halong/g | sed -e s/TebingTinggi/Halong/g | sed -e s/38/35/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Paringin\ Selatan/g | sed -e s/TebingTinggi/ParinginSelatan/g | sed -e s/38/36/g >> model_gabungan
cat models_tt.py  >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BPBD/g | sed -e s/TebingTinggi/BPBD/g | sed -e s/38/39/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPKP/g | sed -e s/TebingTinggi/DPKP/g | sed -e s/38/40/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Disnakertrans/g | sed -e s/TebingTinggi/Disnakertrans/g | sed -e s/38/41/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/DPPKB/g | sed -e s/TebingTinggi/DPPKB/g | sed -e s/38/42/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Kominfo/g | sed -e s/TebingTinggi/Kominfo/g | sed -e s/38/43/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Kearsipan/g | sed -e s/TebingTinggi/Kearsipan/g | sed -e s/38/44/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Perikanan/g | sed -e s/TebingTinggi/Perikanan/g | sed -e s/38/45/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Pariwisata/g | sed -e s/TebingTinggi/Pariwisata/g | sed -e s/38/46/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/Perdagangan/g | sed -e s/TebingTinggi/Perdagangan/g | sed -e s/38/47/g >> model_gabungan
cat models_tt.py | sed -e s/Tebing\ Tinggi/BPPD/g | sed -e s/TebingTinggi/BPPD/g | sed -e s/38/48/g >> model_gabungan
