cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(15238\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
#cat setda.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(13493\,/g -e s/$/\)\;/g > setda_insert.sql
