cvs add 001_SDN_Ajung/*.xml
cvs add 002_SDN_Ambakiang_Hulu/*.xml
cvs add 003_SDN_Aniyungan/*.xml
cvs add 004_SDN_Auh/*.xml
cvs add 005_SDN_Badalungga/*.xml
cvs add 006_SDN_Badalungga_Hilir/*.xml
cvs add 007_SDN_Bakung/*.xml
cvs add 008_SDN_Balida/*.xml
cvs add 009_SDN_Banua_Hanyar/*.xml
cvs add 010_SDN_Baramban/*.xml
cvs add 011_SDN_Baru/*.xml
cvs add 012_SDN_Baruh_Bahinu_Dalam/*.xml
cvs add 013_SDN_Baruh_Bahinu_Luar/*.xml
cvs add 014_SDN_Baruh_Penyambaran_1/*.xml
cvs add 015_SDN_Baruh_Penyambaran_2/*.xml
cvs add 016_SDN_Bata/*.xml
cvs add 017_SDN_Batu_Merah_1/*.xml
cvs add 018_SDN_Batu_Merah_3/*.xml
cvs add 019_SDN_Batu_Piring/*.xml
cvs add 020_SDN_Bayur/*.xml
cvs add 021_SDN_Belanti/*.xml
cvs add 022_SDN_Binjai_Punggal_1/*.xml
cvs add 023_SDN_Binjai_Punggal_2/*.xml
cvs add 024_SDN_Binju/*.xml
cvs add 025_SDN_Binuang_Santang/*.xml
cvs add 026_SDN_Bungur/*.xml
cvs add 027_SDN_Buntu_Karau_1/*.xml
cvs add 028_SDN_Dahai/*.xml
cvs add 029_SDN_Danau_Banta/*.xml
cvs add 030_SDN_Dayak_Pitap/*.xml
cvs add 031_SDN_Galumbang_Juai/*.xml
cvs add 032_SDN_Galumbang_Paringin_Selatan/*.xml
cvs add 033_SDN_Gampa/*.xml
cvs add 034_SDN_Guha_1/*.xml
cvs add 035_SDN_Guha_2/*.xml
cvs add 036_SDN_Gulinggang/*.xml
cvs add 037_SDN_Gunung_Manau/*.xml
cvs add 038_SDN_Gunung_Pandau/*.xml
cvs add 039_SDN_Gunung_Riut_1/*.xml
cvs add 040_SDN_Gunung_Riut_2/*.xml
cvs add 041_SDN_Halong_1/*.xml
cvs add 042_SDN_Halong_2/*.xml
cvs add 043_SDN_Halong_3/*.xml
cvs add 044_SDN_Halubau/*.xml
cvs add 045_SDN_Halubau_Utara/*.xml
cvs add 046_SDN_Hamarung_1/*.xml
cvs add 047_SDN_Hamarung_2/*.xml
cvs add 048_SDN_Hamparaya/*.xml
cvs add 049_SDN_Hauwai_1/*.xml
cvs add 050_SDN_Hauwai_2/*.xml
cvs add 051_SDN_Hilir_Pasar/*.xml
cvs add 052_SDN_Hujan_Amas_1/*.xml
cvs add 053_SDN_Hujan_Amas_2/*.xml
cvs add 054_SDN_Hukai/*.xml
cvs add 055_SDN_Inan/*.xml
cvs add 056_SDN_Jimamun/*.xml
cvs add 057_SDN_Ju_uh/*.xml
cvs add 058_SDN_Juai/*.xml
cvs add 059_SDN_Jungkal/*.xml
cvs add 060_SDN_Kaladan/*.xml
cvs add 061_SDN_Kalahiang/*.xml
cvs add 062_SDN_Kambiyain/*.xml
cvs add 063_SDN_Kandang_Jaya/*.xml
cvs add 064_SDN_Kapul/*.xml
cvs add 065_SDN_Karuh/*.xml
cvs add 066_SDN_Kasai/*.xml
cvs add 067_SDN_Kupang/*.xml
cvs add 068_SDN_Kusambi_Hilir/*.xml
cvs add 069_SDN_Kusambi_Hulu_1/*.xml
cvs add 070_SDN_Kusambi_Hulu_2/*.xml
cvs add 071_SDN_Lajar/*.xml
cvs add 072_SDN_Lalayau_1/*.xml
cvs add 073_SDN_lalayau_2/*.xml
cvs add 074_SDN_Lamida_Atas/*.xml
cvs add 075_SDN_Lampihong_Kanan/*.xml
cvs add 076_SDN_Lampihong_Kiri/*.xml
cvs add 077_SDN_Langkap/*.xml
cvs add 078_SDN_Lasung_Batu_1/*.xml
cvs add 079_SDN_Lasung_Batu_2/*.xml
cvs add 080_SDN_Lingsir/*.xml
cvs add 081_SDN_Lok_Batu/*.xml
cvs add 082_SDN_Lok_Batung/*.xml
cvs add 083_SDN_Lok_Hamawang/*.xml
cvs add 084_SDN_Lok_Panginangan/*.xml
cvs add 085_SDN_Malihu/*.xml
cvs add 086_SDN_Mamantang/*.xml
cvs add 087_SDN_Mampari/*.xml
cvs add 088_SDN_Mangkayahu/*.xml
cvs add 089_SDN_Maningau/*.xml
cvs add 090_SDN_Mantimin_1/*.xml
cvs add 091_SDN_Mantimin_2/*.xml
cvs add 092_SDN_Mantuyan/*.xml
cvs add 093_SDN_Maradap/*.xml
cvs add 094_SDN_Marias/*.xml
cvs add 095_SDN_Matang_Hanau/*.xml
cvs add 096_SDN_Mauya/*.xml
cvs add 097_SDN_Mayanau/*.xml
cvs add 098_SDN_Merah/*.xml
cvs add 099_SDN_Mihu_1/*.xml
cvs add 100_SDN_Mihu_2/*.xml
cvs add 101_SDN_Muara_Jaya/*.xml
cvs add 102_SDN_Muara_Ninian/*.xml
cvs add 103_SDN_Muara_Pitap/*.xml
cvs add 104_SDN_Mundar/*.xml
cvs add 105_SDN_Mungkur_Uyam/*.xml
cvs add 106_SDN_Munjung/*.xml
cvs add 107_SDN_Murung_Abuin/*.xml
cvs add 108_SDN_Murung_Ilung/*.xml
cvs add 109_SDN_Nungka/*.xml
cvs add 110_SDN_Pamurus/*.xml
cvs add 111_SDN_Panaitan/*.xml
cvs add 112_SDN_Panikin/*.xml
cvs add 113_SDN_Paringin_1/*.xml
cvs add 114_SDN_Paringin_2/*.xml
cvs add 115_SDN_Paringin_Selatan_1/*.xml
cvs add 116_SDN_Paringin_Timur/*.xml
cvs add 117_SDN_Pelajau/*.xml
cvs add 118_SDN_Pematang/*.xml
cvs add 119_SDN_Pimping/*.xml
cvs add 120_SDN_Piyait/*.xml
cvs add 121_SDN_Pulantan/*.xml
cvs add 122_SDN_Pulau_Kambang/*.xml
cvs add 123_SDN_Putat_Basiun/*.xml
cvs add 124_SDN_Puyun/*.xml
cvs add 125_SDN_Riwa/*.xml
cvs add 126_SDN_Sei_Kusi/*.xml
cvs add 127_SDN_Simpang_Tiga/*.xml
cvs add 128_SDN_Sirap_1/*.xml
cvs add 129_SDN_Sirap_2/*.xml
cvs add 130_SDN_Sirap_3/*.xml
cvs add 131_SDN_Sumpung/*.xml
cvs add 132_SDN_Sungai_Batung/*.xml
cvs add 133_SDN_Sungai_Hanyar/*.xml
cvs add 134_SDN_Sungai_Ketapi/*.xml
cvs add 135_SDN_Sungai_Pumpung/*.xml
cvs add 136_SDN_Sungai_Tabuk/*.xml
cvs add 137_SDN_Sungsum/*.xml
cvs add 138_SDN_Tabuan_1/*.xml
cvs add 139_SDN_Tabuan_2/*.xml
cvs add 140_SDN_Tampang/*.xml
cvs add 141_SDN_Tanah_Habang_Kanan_1/*.xml
cvs add 142_SDN_Tanah_Habang_Kanan_2/*.xml
cvs add 143_SDN_Tanah_Habang_Kiri/*.xml
cvs add 144_SDN_Tarangan/*.xml
cvs add 145_SDN_Tawahan_1/*.xml
cvs add 146_SDN_Tawahan_2/*.xml
cvs add 147_SDN_Tebing_Tinggi/*.xml
cvs add 148_SDN_Telaga_Purun/*.xml
cvs add 149_SDN_Teluk_Bayur_2/*.xml
cvs add 150_SDN_Teluk_Bayur_3/*.xml
cvs add 151_SDN_Teluk_Mesjid_1/*.xml
cvs add 152_SDN_Teluk_Mesjid_2/*.xml
cvs add 153_SDN_Tigarun/*.xml
cvs add 154_SDN_Timbun_Tulang/*.xml
cvs add 155_SDN_Tundakan/*.xml
cvs add 156_SDN_Tundi/*.xml
cvs add 157_SDN_U_ungan/*.xml
cvs add 158_SDN_Uren_1/*.xml
cvs add 159_SDN_Wangkili/*.xml
cvs add 160_SKB_Balangan/*.xml
cvs add 161_SMAN_1_Awayan/*.xml
cvs add 162_SMAN_1_Halong/*.xml
cvs add 163_SMAN_1_Juai/*.xml
cvs add 164_SMAN_1_Lampihong/*.xml
cvs add 165_SMAN_1_Paringin/*.xml
cvs add 166_SMAN_1_Tebing_Tinggi/*.xml
cvs add 167_SMAN_2_Halong/*.xml
cvs add 168_SMAN_2_Juai/*.xml
cvs add 169_SMAN_2_Paringin/*.xml
cvs add 170_SMK_PPN_Paringin/*.xml
cvs add 171_SMKN_1_Batumandi/*.xml
cvs add 172_SMKN_1_Paringin/*.xml
cvs add 173_SMPN_1_Awayan/*.xml
cvs add 174_SMPN_1_Batumandi/*.xml
cvs add 175_SMPN_1_Halong/*.xml
cvs add 176_SMPN_1_Juai/*.xml
cvs add 177_SMPN_1_Lampihong/*.xml
cvs add 178_SMPN_1_Paringin/*.xml
cvs add 179_SMPN_2_Awayan/*.xml
cvs add 180_SMPN_2_Batumandi/*.xml
cvs add 181_SMPN_2_Halong/*.xml
cvs add 182_SMPN_2_Juai/*.xml
cvs add 183_SMPN_2_Lampihong/*.xml
cvs add 184_SMPN_2_Paringin/*.xml
cvs add 185_SMPN_3_Awayan/*.xml
cvs add 186_SMPN_3_Batumandi/*.xml
cvs add 187_SMPN_3_Halong/*.xml
cvs add 188_SMPN_3_Paringin/*.xml
cvs add 189_SMPN_4_Awayan/*.xml
cvs add 190_SMPN_4_Batumandi/*.xml
cvs add 191_SMPN_4_Halong/*.xml
cvs add 192_SMPN_4_Paringin/*.xml
cvs add 193_SMPN_5_Halong/*.xml
cvs add 194_SMPN_5_Paringin/*.xml
cvs add 195_SMPN_6_Halong_Satu_Atap/*.xml
cvs add 196_SMPN_Satu_Atap_Libaru_Sungkai/*.xml
cvs add 197_SMPS_Ikhwanul_Muslimin/*.xml
cvs add 198_TK_Harapan_Bangsa/*.xml
cvs add 199_TK_Negeri_Pembina_Awayan/*.xml
cvs add 200_TK_Negeri_Pembina_Batumandi/*.xml
cvs add 201_TK_Negeri_Pembina_Juai/*.xml
cvs add 202_TK_Negeri_Pembina_Paringin/*.xml
cvs add 203_TK_Negeri_Pembina_Paringin_Selatan/*.xml
cvs add 204_SDLB_Negeri_Paringin/*.xml
cvs add 205_UPT_Kecamatan_Tebing_Tinggi/*.xml
cvs add 206_UPT_Kecamatan_Paringin_Selatan/*.xml
cvs add 207_UPT_Kecamatan_Paringin/*.xml
cvs add 208_UPT_Kecamatan_Lampihong/*.xml
cvs add 209_UPT_Kecamatan_Juai/*.xml
cvs add 210_UPT_Kecamatan_Halong/*.xml
cvs add 211_UPT_Kecamatan_Batumandi/*.xml
cvs add 212_UPT_Kecamatan_Awayan/*.xml
cvs add 213_MIN_Tariwin/*.xml
cvs add 214_PAUD_Terpadu_Awayan/*.xml
cvs add 215_Rumah_Pintar/*.xml
cvs add 216_SDIT_Darul_Fikri/*.xml
cvs add 217_SD_Kecil_Ambata/*.xml
cvs add 218_SD_Kecil_Ampinang/*.xml
cvs add 219_SD_Kecil_Hampang/*.xml
cvs add 220_SD_Kecil_Kurihai/*.xml
cvs add 221_SD_Kecil_Libaru_Sungkai/*.xml
cvs add 222_SD_Kecil_Mabulan/*.xml
cvs add 223_SD_Kecil_Papuyuan/*.xml
cvs add 224_SD_Kecil_Rantau_Paku/*.xml
cvs add 225_SD_Kecil_Raranum/*.xml
cvs add 226_SD_Kecil_Simpang_Nadong/*.xml
cvs add 227_SD_Kecil_Tampaan/*.xml
cvs add 228_SD_Kecil_Tanjungan_Jelamu/*.xml
cvs add 229_SD_Kecil_Tinggar/*.xml
cvs add 230_SDK_Andamai/*.xml
cvs add 231_SDK_Mapat/*.xml
cvs add 232_SDK_Sawang/*.xml
cvs add 233_SDK_Sisirin/*.xml
