cvs add 001_SDN_Ajung/*.php
cvs add 002_SDN_Ambakiang_Hulu/*.php
cvs add 003_SDN_Aniyungan/*.php
cvs add 004_SDN_Auh/*.php
cvs add 005_SDN_Badalungga/*.php
cvs add 006_SDN_Badalungga_Hilir/*.php
cvs add 007_SDN_Bakung/*.php
cvs add 008_SDN_Balida/*.php
cvs add 009_SDN_Banua_Hanyar/*.php
cvs add 010_SDN_Baramban/*.php
cvs add 011_SDN_Baru/*.php
cvs add 012_SDN_Baruh_Bahinu_Dalam/*.php
cvs add 013_SDN_Baruh_Bahinu_Luar/*.php
cvs add 014_SDN_Baruh_Penyambaran_1/*.php
cvs add 015_SDN_Baruh_Penyambaran_2/*.php
cvs add 016_SDN_Bata/*.php
cvs add 017_SDN_Batu_Merah_1/*.php
cvs add 018_SDN_Batu_Merah_3/*.php
cvs add 019_SDN_Batu_Piring/*.php
cvs add 020_SDN_Bayur/*.php
cvs add 021_SDN_Belanti/*.php
cvs add 022_SDN_Binjai_Punggal_1/*.php
cvs add 023_SDN_Binjai_Punggal_2/*.php
cvs add 024_SDN_Binju/*.php
cvs add 025_SDN_Binuang_Santang/*.php
cvs add 026_SDN_Bungur/*.php
cvs add 027_SDN_Buntu_Karau_1/*.php
cvs add 028_SDN_Dahai/*.php
cvs add 029_SDN_Danau_Banta/*.php
cvs add 030_SDN_Dayak_Pitap/*.php
cvs add 031_SDN_Galumbang_Juai/*.php
cvs add 032_SDN_Galumbang_Paringin_Selatan/*.php
cvs add 033_SDN_Gampa/*.php
cvs add 034_SDN_Guha_1/*.php
cvs add 035_SDN_Guha_2/*.php
cvs add 036_SDN_Gulinggang/*.php
cvs add 037_SDN_Gunung_Manau/*.php
cvs add 038_SDN_Gunung_Pandau/*.php
cvs add 039_SDN_Gunung_Riut_1/*.php
cvs add 040_SDN_Gunung_Riut_2/*.php
cvs add 041_SDN_Halong_1/*.php
cvs add 042_SDN_Halong_2/*.php
cvs add 043_SDN_Halong_3/*.php
cvs add 044_SDN_Halubau/*.php
cvs add 045_SDN_Halubau_Utara/*.php
cvs add 046_SDN_Hamarung_1/*.php
cvs add 047_SDN_Hamarung_2/*.php
cvs add 048_SDN_Hamparaya/*.php
cvs add 049_SDN_Hauwai_1/*.php
cvs add 050_SDN_Hauwai_2/*.php
cvs add 051_SDN_Hilir_Pasar/*.php
cvs add 052_SDN_Hujan_Amas_1/*.php
cvs add 053_SDN_Hujan_Amas_2/*.php
cvs add 054_SDN_Hukai/*.php
cvs add 055_SDN_Inan/*.php
cvs add 056_SDN_Jimamun/*.php
cvs add 057_SDN_Ju_uh/*.php
cvs add 058_SDN_Juai/*.php
cvs add 059_SDN_Jungkal/*.php
cvs add 060_SDN_Kaladan/*.php
cvs add 061_SDN_Kalahiang/*.php
cvs add 062_SDN_Kambiyain/*.php
cvs add 063_SDN_Kandang_Jaya/*.php
cvs add 064_SDN_Kapul/*.php
cvs add 065_SDN_Karuh/*.php
cvs add 066_SDN_Kasai/*.php
cvs add 067_SDN_Kupang/*.php
cvs add 068_SDN_Kusambi_Hilir/*.php
cvs add 069_SDN_Kusambi_Hulu_1/*.php
cvs add 070_SDN_Kusambi_Hulu_2/*.php
cvs add 071_SDN_Lajar/*.php
cvs add 072_SDN_Lalayau_1/*.php
cvs add 073_SDN_lalayau_2/*.php
cvs add 074_SDN_Lamida_Atas/*.php
cvs add 075_SDN_Lampihong_Kanan/*.php
cvs add 076_SDN_Lampihong_Kiri/*.php
cvs add 077_SDN_Langkap/*.php
cvs add 078_SDN_Lasung_Batu_1/*.php
cvs add 079_SDN_Lasung_Batu_2/*.php
cvs add 080_SDN_Lingsir/*.php
cvs add 081_SDN_Lok_Batu/*.php
cvs add 082_SDN_Lok_Batung/*.php
cvs add 083_SDN_Lok_Hamawang/*.php
cvs add 084_SDN_Lok_Panginangan/*.php
cvs add 085_SDN_Malihu/*.php
cvs add 086_SDN_Mamantang/*.php
cvs add 087_SDN_Mampari/*.php
cvs add 088_SDN_Mangkayahu/*.php
cvs add 089_SDN_Maningau/*.php
cvs add 090_SDN_Mantimin_1/*.php
cvs add 091_SDN_Mantimin_2/*.php
cvs add 092_SDN_Mantuyan/*.php
cvs add 093_SDN_Maradap/*.php
cvs add 094_SDN_Marias/*.php
cvs add 095_SDN_Matang_Hanau/*.php
cvs add 096_SDN_Mauya/*.php
cvs add 097_SDN_Mayanau/*.php
cvs add 098_SDN_Merah/*.php
cvs add 099_SDN_Mihu_1/*.php
cvs add 100_SDN_Mihu_2/*.php
cvs add 101_SDN_Muara_Jaya/*.php
cvs add 102_SDN_Muara_Ninian/*.php
cvs add 103_SDN_Muara_Pitap/*.php
cvs add 104_SDN_Mundar/*.php
cvs add 105_SDN_Mungkur_Uyam/*.php
cvs add 106_SDN_Munjung/*.php
cvs add 107_SDN_Murung_Abuin/*.php
cvs add 108_SDN_Murung_Ilung/*.php
cvs add 109_SDN_Nungka/*.php
cvs add 110_SDN_Pamurus/*.php
cvs add 111_SDN_Panaitan/*.php
cvs add 112_SDN_Panikin/*.php
cvs add 113_SDN_Paringin_1/*.php
cvs add 114_SDN_Paringin_2/*.php
cvs add 115_SDN_Paringin_Selatan_1/*.php
cvs add 116_SDN_Paringin_Timur/*.php
cvs add 117_SDN_Pelajau/*.php
cvs add 118_SDN_Pematang/*.php
cvs add 119_SDN_Pimping/*.php
cvs add 120_SDN_Piyait/*.php
cvs add 121_SDN_Pulantan/*.php
cvs add 122_SDN_Pulau_Kambang/*.php
cvs add 123_SDN_Putat_Basiun/*.php
cvs add 124_SDN_Puyun/*.php
cvs add 125_SDN_Riwa/*.php
cvs add 126_SDN_Sei_Kusi/*.php
cvs add 127_SDN_Simpang_Tiga/*.php
cvs add 128_SDN_Sirap_1/*.php
cvs add 129_SDN_Sirap_2/*.php
cvs add 130_SDN_Sirap_3/*.php
cvs add 131_SDN_Sumpung/*.php
cvs add 132_SDN_Sungai_Batung/*.php
cvs add 133_SDN_Sungai_Hanyar/*.php
cvs add 134_SDN_Sungai_Ketapi/*.php
cvs add 135_SDN_Sungai_Pumpung/*.php
cvs add 136_SDN_Sungai_Tabuk/*.php
cvs add 137_SDN_Sungsum/*.php
cvs add 138_SDN_Tabuan_1/*.php
cvs add 139_SDN_Tabuan_2/*.php
cvs add 140_SDN_Tampang/*.php
cvs add 141_SDN_Tanah_Habang_Kanan_1/*.php
cvs add 142_SDN_Tanah_Habang_Kanan_2/*.php
cvs add 143_SDN_Tanah_Habang_Kiri/*.php
cvs add 144_SDN_Tarangan/*.php
cvs add 145_SDN_Tawahan_1/*.php
cvs add 146_SDN_Tawahan_2/*.php
cvs add 147_SDN_Tebing_Tinggi/*.php
cvs add 148_SDN_Telaga_Purun/*.php
cvs add 149_SDN_Teluk_Bayur_2/*.php
cvs add 150_SDN_Teluk_Bayur_3/*.php
cvs add 151_SDN_Teluk_Mesjid_1/*.php
cvs add 152_SDN_Teluk_Mesjid_2/*.php
cvs add 153_SDN_Tigarun/*.php
cvs add 154_SDN_Timbun_Tulang/*.php
cvs add 155_SDN_Tundakan/*.php
cvs add 156_SDN_Tundi/*.php
cvs add 157_SDN_U_ungan/*.php
cvs add 158_SDN_Uren_1/*.php
cvs add 159_SDN_Wangkili/*.php
cvs add 160_SKB_Balangan/*.php
cvs add 161_SMAN_1_Awayan/*.php
cvs add 162_SMAN_1_Halong/*.php
cvs add 163_SMAN_1_Juai/*.php
cvs add 164_SMAN_1_Lampihong/*.php
cvs add 165_SMAN_1_Paringin/*.php
cvs add 166_SMAN_1_Tebing_Tinggi/*.php
cvs add 167_SMAN_2_Halong/*.php
cvs add 168_SMAN_2_Juai/*.php
cvs add 169_SMAN_2_Paringin/*.php
cvs add 170_SMK_PPN_Paringin/*.php
cvs add 171_SMKN_1_Batumandi/*.php
cvs add 172_SMKN_1_Paringin/*.php
cvs add 173_SMPN_1_Awayan/*.php
cvs add 174_SMPN_1_Batumandi/*.php
cvs add 175_SMPN_1_Halong/*.php
cvs add 176_SMPN_1_Juai/*.php
cvs add 177_SMPN_1_Lampihong/*.php
cvs add 178_SMPN_1_Paringin/*.php
cvs add 179_SMPN_2_Awayan/*.php
cvs add 180_SMPN_2_Batumandi/*.php
cvs add 181_SMPN_2_Halong/*.php
cvs add 182_SMPN_2_Juai/*.php
cvs add 183_SMPN_2_Lampihong/*.php
cvs add 184_SMPN_2_Paringin/*.php
cvs add 185_SMPN_3_Awayan/*.php
cvs add 186_SMPN_3_Batumandi/*.php
cvs add 187_SMPN_3_Halong/*.php
cvs add 188_SMPN_3_Paringin/*.php
cvs add 189_SMPN_4_Awayan/*.php
cvs add 190_SMPN_4_Batumandi/*.php
cvs add 191_SMPN_4_Halong/*.php
cvs add 192_SMPN_4_Paringin/*.php
cvs add 193_SMPN_5_Halong/*.php
cvs add 194_SMPN_5_Paringin/*.php
cvs add 195_SMPN_6_Halong_Satu_Atap/*.php
cvs add 196_SMPN_Satu_Atap_Libaru_Sungkai/*.php
cvs add 197_SMPS_Ikhwanul_Muslimin/*.php
cvs add 198_TK_Harapan_Bangsa/*.php
cvs add 199_TK_Negeri_Pembina_Awayan/*.php
cvs add 200_TK_Negeri_Pembina_Batumandi/*.php
cvs add 201_TK_Negeri_Pembina_Juai/*.php
cvs add 202_TK_Negeri_Pembina_Paringin/*.php
cvs add 203_TK_Negeri_Pembina_Paringin_Selatan/*.php
cvs add 204_SDLB_Negeri_Paringin/*.php
cvs add 205_UPT_Kecamatan_Tebing_Tinggi/*.php
cvs add 206_UPT_Kecamatan_Paringin_Selatan/*.php
cvs add 207_UPT_Kecamatan_Paringin/*.php
cvs add 208_UPT_Kecamatan_Lampihong/*.php
cvs add 209_UPT_Kecamatan_Juai/*.php
cvs add 210_UPT_Kecamatan_Halong/*.php
cvs add 211_UPT_Kecamatan_Batumandi/*.php
cvs add 212_UPT_Kecamatan_Awayan/*.php
cvs add 213_MIN_Tariwin/*.php
cvs add 214_PAUD_Terpadu_Awayan/*.php
cvs add 215_Rumah_Pintar/*.php
cvs add 216_SDIT_Darul_Fikri/*.php
cvs add 217_SD_Kecil_Ambata/*.php
cvs add 218_SD_Kecil_Ampinang/*.php
cvs add 219_SD_Kecil_Hampang/*.php
cvs add 220_SD_Kecil_Kurihai/*.php
cvs add 221_SD_Kecil_Libaru_Sungkai/*.php
cvs add 222_SD_Kecil_Mabulan/*.php
cvs add 223_SD_Kecil_Papuyuan/*.php
cvs add 224_SD_Kecil_Rantau_Paku/*.php
cvs add 225_SD_Kecil_Raranum/*.php
cvs add 226_SD_Kecil_Simpang_Nadong/*.php
cvs add 227_SD_Kecil_Tampaan/*.php
cvs add 228_SD_Kecil_Tanjungan_Jelamu/*.php
cvs add 229_SD_Kecil_Tinggar/*.php
cvs add 230_SDK_Andamai/*.php
cvs add 231_SDK_Mapat/*.php
cvs add 232_SDK_Sawang/*.php
cvs add 233_SDK_Sisirin/*.php
