cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dpupr/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>3/g >  03_dpupr/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dishub/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>4/g >  04_dishub/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dinkes/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>5/g >  05_dinkes/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/disdik/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>7/g >  07_disdik/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/perpustakaan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>8/g >  08_perpustakaan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/sosial/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>9/g >  09_sosial/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dpmd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>10/g >  10_dpmd/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dpppa/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>11/g >  11_dpppa/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dukcatpil/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>12/g >  12_dukcatpil/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/pertanian/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>13/g >  13_pertanian/daftar_persediaan_skpd.xml
#cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\15/g >  15_dkp/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dkukmp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>16/g >  16_dkukmp/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dpmptsp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>18/g >  18_dpmptsp/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/bkd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>19/g >  19_bkd/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/inspektorat/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>20/g >  20_inspektorat/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/bappeda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>21/g >  21_bappeda/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dlh/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>22/g >  22_dlh/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dko/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>23/g >  23_dko/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/kesbangpol/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>24/g >  24_kesbangpol/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/satpolpp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>25/g >  25_satpolpp/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/bkppd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>26/g >  26_bkppd/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/paringin/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>28/g >  28_paringin/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/lampihong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>31/g >  31_lampihong/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/batumandi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>32/g >  32_batumandi/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/juai/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>33/g >  33_juai/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/awayan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>34/g >  34_awayan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/halong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>35/g >  35_halong/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/paringinselatan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>36/g >  36_paringinselatan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/tebingtinggi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>38/g >  38_tebingtinggi/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/bpbd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>39/g >  39_bpbd/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dpkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>40/g >  40_dpkp/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/disnakertrans/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>41/g >  41_disnakertrans/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/dppkb/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>42/g >  42_dppkb/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/kominfo/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>43/g >  43_kominfo/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/kearsipan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>44/g >  44_kearsipan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/perikanan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>45/g >  45_perikanan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/pariwisata/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>46/g >  46_pariwisata/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/perdagangan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>47/g >  47_perdagangan/daftar_persediaan_skpd.xml
cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/setwan/bppd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>48/g >  48_bppd/daftar_persediaan_skpd.xml
#cat 01_setwan/daftar_persediaan_skpd.xml | sed -e s/barang4_setwan/barang_rinci_kabupaten/g > kabupaten/daftar_persediaan_skpd.xml
